### ISSUE TITLE
No module named 'TDNN'

### ISSUE THREAD

**Issue by Lolologist** [carpedm20/lstm-char-cnn-tensorflow#17]
Using Python 3.5

I tried to run this project with its basic settings and cannot even run main.py as it claims there's a missing module.
Though __init__.py in the models folder says it can't find TDNN, I verified that the file is indeed there.

C:\Users\dbishop\Desktop\lstm-char-cnn-tensorflow-master>python main.py --dataset ptb
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from models import LSTMTDNN
  File "C:\Users\dbishop\Desktop\lstm-char-cnn-tensorflow-master\models\__init__.py", line 1, in <module>
    from TDNN import TDNN
ImportError: No module named 'TDNN'

**Comment by Lolologist** [comment]
Issue seems to come from using python 3. The project claims to be python3 compatible, but I see xrange instead of range all over, and had to use python3-style imports to get around the issue above.
How do I use this project with python 3?

**Comment by qZhang88** [comment]
@Lolologist 

Same issue occurs for me. Seems to be import issue. Solving this by:
Change: 
    from TDNN import TDNN
to:
    from .TDNN import TDNN

there are also some other import statements you have to change too

**Comment by jingweimo** [comment]
@Lologist: I use python3.5, and still got the import error: No module named 'base', after following your suggestions.
