### ISSUE TITLE
Failed to train on the ptb dataset

### ISSUE THREAD

**Issue by ygoncharov** [carpedm20/lstm-char-cnn-tensorflow#2]
Python 2.7.6 on Ubuntu 14.04.3

$ python main.py --dataset ptb

Reshaping tensors...
data load done. Number of batches in train: 265, val: 21, test: 23
Word vocab size: 10001, Char vocab size: 51, Max word length (incl. padding): 21
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 11, in run
    sys.exit(main(sys.argv))
  File "main.py", line 57, in main
    data_dir=FLAGS.data_dir)
  File "/mnt/win/lstm-char-cnn-tensorflow/models/LSTMTDNN.py", line 86, in __init__
    self.prepare_model()
  File "/mnt/win/lstm-char-cnn-tensorflow/models/LSTMTDNN.py", line 144, in prepare_model
    cnn_output = highway(cnn_output, cnn_output.get_shape()[1], self.highway_layers, 0)
  File "/mnt/win/lstm-char-cnn-tensorflow/models/ops.py", line 28, in highway
    output = f(rnn_cell.linear(output, size, 0, scope='output_lin_%d' % idx))
TypeError: 'module' object is not callable

**Comment by ygoncharov** [comment]
Fixed by upgrading TensorFlow to 0.6
